; PHP Configuration for Development

display_errors = on
display_startup_errors = on
error_reporting = E_ALL
log_errors_max_len = 0

date.timezone = "Europe/Ljubljana"
memory_limit = 256M
;memory_limit = 512M
max_execution_time = 60
max_input_time = 60
post_max_size = 32M
upload_max_filesize = 24M
max_input_vars = 10000

; Redirect emails to Mailpit
sendmail_path = "/usr/bin/msmtp --host=mailpit --port=1025 --from=dev@local --read-recipients"